# --- Create minimal image to download the data
FROM alpine:3.7 AS data
RUN apk update
RUN apk add wget
RUN wget https://s3-us-west-2.amazonaws.com/tegola/bonn_osm.sql.tgz
RUN tar xzf bonn_osm.sql.tgz

# --- Create the sample data
FROM mdillon/postgis:9.6
COPY --from=data bonn_osm.sql /tmp/bonn_osm.sql
RUN su tegola && postgres
RUN createdb bonn
RUN psql bonn < /tmp/bonn_osm.sql
RUN psql -c "CREATE USER tegola;"
RUN psql -d bonn -c "GRANT SELECT ON ALL TABLES IN SCHEMA public TO tegola;"
RUN rm /tmp/bonn_osm.sql
