version: '3'
services:
    postgis:
        image: mdillon/postgis:9.6
        environment:
            - POSTGRES_USER=${PG_USER}
            - POSTGRES_PASSWORD=${PG_PASS}
            - POSTGRES_DB=geopostgis
        ports:
            - "5432:5432"
        volumes:
            - ${PATH_PREFIX}/db/data:/var/lib/postgresql/data

    tegola:
        build:
            context: .
