#	Natural Earth
[[providers]]
name = "ne"
type = "postgis"
host = "natural_earth"
port = 5432
database = "tegola-ne-db"
user = "tegola-ne-user"
password = "tegola-ne-password"

	[[providers.layers]]
	name = "ne_110m_populated_places"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, scalerank, labelrank, name, min_zoom, featurecla, rank_max FROM ne_110m_populated_places WHERE wkb_geometry && !BBOX!"

	[[providers.layers]]
	name = "ne_50m_populated_places"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, scalerank, labelrank, name, min_zoom, featurecla, rank_max FROM ne_50m_populated_places WHERE wkb_geometry && !BBOX!"

	[[providers.layers]]
	name = "ne_10m_populated_places"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, scalerank, labelrank, name, min_zoom, featurecla, rank_max FROM ne_10m_populated_places WHERE wkb_geometry && !BBOX!"

	[[providers.layers]]
	name = "ne_10m_admin_0_label_points"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, sr_subunit, scalerank FROM ne_10m_admin_0_label_points WHERE wkb_geometry && !BBOX!"

	[[providers.layers]]
	name = "ne_10m_admin_1_label_points"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, name, scalerank FROM ne_10m_admin_1_label_points WHERE wkb_geometry && !BBOX!"

	[[providers.layers]]
	name = "ne_110m_admin_0_boundary_lines_land"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, featurecla, name, min_zoom FROM ne_110m_admin_0_boundary_lines_land WHERE wkb_geometry && !BBOX!"

	[[providers.layers]]
	name = "ne_50m_admin_0_boundary_lines_land"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, featurecla, name, min_zoom FROM ne_50m_admin_0_boundary_lines_land WHERE wkb_geometry && !BBOX!"

	[[providers.layers]]
	name = "ne_10m_admin_0_boundary_lines_land"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, featurecla, name, min_zoom FROM ne_10m_admin_0_boundary_lines_land WHERE wkb_geometry && !BBOX!"

	[[providers.layers]]
	name = "ne_50m_admin_0_boundary_lines_disputed_areas"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, featurecla, name, min_zoom FROM ne_50m_admin_0_boundary_lines_disputed_areas WHERE wkb_geometry && !BBOX!"

	[[providers.layers]]
	name = "ne_10m_admin_0_boundary_lines_disputed_areas"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, featurecla, name, min_zoom FROM ne_10m_admin_0_boundary_lines_disputed_areas WHERE wkb_geometry && !BBOX!"

	[[providers.layers]]
	name = "ne_110m_admin_0_countries"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, featurecla, name, name_long, abbrev, adm0_a3, min_zoom, min_label, max_label FROM ne_110m_admin_0_countries WHERE wkb_geometry && !BBOX!"

	[[providers.layers]]
	name = "ne_50m_admin_0_countries"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, featurecla, name, name_long, abbrev, adm0_a3, min_zoom, min_label, max_label FROM ne_50m_admin_0_countries WHERE wkb_geometry && !BBOX!"

	[[providers.layers]]
	name = "ne_10m_admin_0_countries"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, featurecla, name, name_long, abbrev, adm0_a3, min_zoom, min_label, max_label FROM ne_10m_admin_0_countries WHERE wkb_geometry && !BBOX!"

	[[providers.layers]]
	name = "ne_110m_admin_1_states_provinces_lines"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, featurecla, name, adm0_name, min_zoom FROM ne_110m_admin_1_states_provinces_lines WHERE wkb_geometry && !BBOX!"

    [[providers.layers]]
	name = "ne_50m_admin_1_states_provinces_lines"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, featurecla, name, adm0_name, min_zoom FROM ne_50m_admin_1_states_provinces_lines WHERE wkb_geometry && !BBOX!"

	[[providers.layers]]
	name = "ne_10m_admin_1_states_provinces_lines"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, featurecla, name, adm0_name, min_zoom, min_label FROM ne_10m_admin_1_states_provinces_lines WHERE wkb_geometry && !BBOX!"

	[[providers.layers]]
	name = "ne_110m_land"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, featurecla, min_zoom FROM ne_110m_land WHERE wkb_geometry && !BBOX!"

	[[providers.layers]]
	name = "ne_50m_land"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, featurecla, min_zoom FROM ne_50m_land WHERE wkb_geometry && !BBOX!"

	[[providers.layers]]
	name = "ne_10m_land"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, featurecla, min_zoom FROM ne_10m_land WHERE wkb_geometry && !BBOX!"

	[[providers.layers]]
	name = "ne_50m_admin_1_states_provinces_lakes"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, featurecla, name, postal, min_zoom, min_label FROM ne_50m_admin_1_states_provinces_lakes WHERE wkb_geometry && !BBOX!"

	[[providers.layers]]
	name = "ne_10m_roads_3"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, name, min_zoom, min_label, type, label FROM ne_10m_roads WHERE min_zoom < 5 AND type <> 'Ferry Route' AND wkb_geometry && !BBOX!"

	[[providers.layers]]
	name = "ne_10m_roads_5"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, name, min_zoom, min_label, type, label FROM ne_10m_roads WHERE min_zoom <= 7  AND type <> 'Ferry Route' AND wkb_geometry && !BBOX!"


[[maps]]
name = "osm"
attribution = "Open Street Map" # map attribution
center = [-76.275329586789, 39.153492567373, 8.0] # optional center value. part of the TileJSON spec

	[[maps.layers]]
	name = "populated_places"
	provider_layer = "ne.ne_110m_populated_places"
	min_zoom = 0
	max_zoom = 2

	[[maps.layers]]
	name = "populated_places"
	provider_layer = "ne.ne_50m_populated_places"
	min_zoom = 3
	max_zoom = 4

	[[maps.layers]]
	name = "populated_places"
	provider_layer = "ne.ne_10m_populated_places"
	min_zoom = 5
	max_zoom = 20

	[[maps.layers]]
	name = "country_lines"
	provider_layer = "ne.ne_110m_admin_0_boundary_lines_land"
	min_zoom = 0
	max_zoom = 2

	[[maps.layers]]
	name = "country_lines"
	provider_layer = "ne.ne_50m_admin_0_boundary_lines_land"
	min_zoom = 3
	max_zoom = 4

	[[maps.layers]]
	name = "country_lines"
	provider_layer = "ne.ne_10m_admin_0_boundary_lines_land"
	min_zoom = 5
	max_zoom = 10

	[[maps.layers]]
	name = "country_lines_disputed"
	provider_layer = "ne.ne_50m_admin_0_boundary_lines_disputed_areas"
	min_zoom = 3
	max_zoom = 4

	[[maps.layers]]
	name = "country_lines_disputed"
	provider_layer = "ne.ne_10m_admin_0_boundary_lines_disputed_areas"
	min_zoom = 5
	max_zoom = 10

	[[maps.layers]]
	name = "country_label_points"
	provider_layer = "ne.ne_10m_admin_0_label_points"
	min_zoom = 3
	max_zoom = 20

	[[maps.layers]]
	name = "country_polygons"
	provider_layer = "ne.ne_110m_admin_0_countries"
	min_zoom = 0
	max_zoom = 2

	[[maps.layers]]
	name = "country_polygons"
	provider_layer = "ne.ne_50m_admin_0_countries"
	min_zoom = 3
	max_zoom = 4

	[[maps.layers]]
	name = "country_polygons"
	provider_layer = "ne.ne_10m_admin_0_countries"
	min_zoom = 5
	max_zoom = 10

	[[maps.layers]]
	name = "state_lines"
	provider_layer = "ne.ne_110m_admin_1_states_provinces_lines"
	min_zoom = 0
	max_zoom = 2

	[[maps.layers]]
	name = "state_lines"
	provider_layer = "ne.ne_50m_admin_1_states_provinces_lines"
	min_zoom = 3
	max_zoom = 4

	[[maps.layers]]
	name = "state_lines"
	provider_layer = "ne.ne_10m_admin_1_states_provinces_lines"
	min_zoom = 5
	max_zoom = 10

	# Land Polygons
	[[maps.layers]]
	name = "land"
	provider_layer = "ne.ne_110m_land"
	min_zoom = 0
	max_zoom = 2

	[[maps.layers]]
	name = "land"
	provider_layer = "ne.ne_50m_land"
	min_zoom = 3
	max_zoom = 4

	[[maps.layers]]
	name = "land"
	provider_layer = "ne.ne_10m_land"
	min_zoom = 5
	max_zoom = 7

	[[maps.layers]]
	name = "land"
	provider_layer = "osm.land_8-20"
	min_zoom = 8
	max_zoom = 20

	[[maps.layers]]
	name = "admin_lines"
	provider_layer = "osm.admin_boundaries_8-12"
	min_zoom = 8
	max_zoom = 12

	[[maps.layers]]
	name = "admin_lines"
	provider_layer = "osm.admin_boundaries_13-20"
	min_zoom = 13
	max_zoom = 20

	[[maps.layers]]
	name = "state_label_points"
	provider_layer = "ne.ne_10m_admin_1_label_points"
	min_zoom = 3
	max_zoom = 20

	# Land Use
	[[maps.layers]]
	name = "landuse_areas"
	provider_layer = "osm.landuse_areas_gen0"
	min_zoom = 3
	max_zoom = 5

	[[maps.layers]]
	name = "landuse_areas"
	provider_layer = "osm.landuse_areas_gen0_6"
	min_zoom = 6
	max_zoom = 9

	[[maps.layers]]
	name = "landuse_areas"
	provider_layer = "osm.landuse_areas_gen1"
	min_zoom = 10
	max_zoom = 12

	[[maps.layers]]
	name = "landuse_areas"
	provider_layer = "osm.landuse_areas"
	min_zoom = 13
	max_zoom = 20

	# Water Areas
	[[maps.layers]]
	name = "water_areas"
	provider_layer = "osm.water_areas_gen0"
	min_zoom = 3
	max_zoom = 5

	[[maps.layers]]
	name = "water_areas"
	provider_layer = "osm.water_areas_gen0_6"
	min_zoom = 6
	max_zoom = 9

	[[maps.layers]]
	name = "water_areas"
	provider_layer = "osm.water_areas_gen1"
	min_zoom = 10
	max_zoom = 12

	[[maps.layers]]
	name = "water_areas"
	provider_layer = "osm.water_areas"
	min_zoom = 13
	max_zoom = 20

	# Water Lines
	[[maps.layers]]
	name = "water_lines"
	provider_layer = "osm.water_lines_gen0"
	min_zoom = 8
	max_zoom = 12

	[[maps.layers]]
	name = "water_lines"
	provider_layer = "osm.water_lines_gen1"
	min_zoom = 13
	max_zoom = 14

	[[maps.layers]]
	name = "water_lines"
	provider_layer = "osm.water_lines"
	min_zoom = 15
	max_zoom = 20

	# Transport Lines (Roads, Rail, Aviation)
	[[maps.layers]]
	name = "transport_lines"
	provider_layer = "ne.ne_10m_roads_3"
	min_zoom = 3
	max_zoom = 4

	[[maps.layers]]
	name = "transport_lines"
	provider_layer = "ne.ne_10m_roads_5"
	min_zoom = 5
	max_zoom = 6

	[[maps.layers]]
	name = "transport_lines"
	provider_layer = "osm.transport_lines_gen0"
	min_zoom = 7
	max_zoom = 8

	[[maps.layers]]
	name = "transport_lines"
	provider_layer = "osm.transport_lines_gen1"
	min_zoom = 9
	max_zoom = 10

	[[maps.layers]]
	name = "transport_lines"
	provider_layer = "osm.transport_lines_11-12"
	min_zoom = 11
	max_zoom = 12

	[[maps.layers]]
	name = "transport_lines"
	provider_layer = "osm.transport_lines_13"
	min_zoom = 13
	max_zoom = 13

	[[maps.layers]]
	name = "transport_lines"
	provider_layer = "osm.transport_lines_14-20"
	min_zoom = 14
	max_zoom = 20

	# Transport Areas
	[[maps.layers]]
	name = "transport_areas"
	provider_layer = "osm.transport_areas"
	min_zoom = 12
	max_zoom = 20

	# Transport Points
	[[maps.layers]]
	name = "transport_points"
	provider_layer = "osm.transport_points"
	min_zoom = 14
	max_zoom = 20

	# Amenity Areas
	[[maps.layers]]
	name = "amenity_areas"
	provider_layer = "osm.amenity_areas"
	min_zoom = 14
	max_zoom = 20

	# Amenity Points
	[[maps.layers]]
	name = "amenity_points"
	provider_layer = "osm.amenity_points"
	min_zoom = 14
	max_zoom = 20

	# Other Points
	[[maps.layers]]
	name = "other_points"
	provider_layer = "osm.other_points"
	min_zoom = 14
	max_zoom = 20

	# Other Lines
	[[maps.layers]]
	name = "other_lines"
	provider_layer = "osm.other_lines"
	min_zoom = 14
	max_zoom = 20

	# Other Areas
	[[maps.layers]]
	name = "other_areas"
	provider_layer = "osm.other_areas_filter"
	min_zoom = 6
	max_zoom = 8

	[[maps.layers]]
	name = "other_areas"
	provider_layer = "osm.other_areas"
	min_zoom = 9
	max_zoom = 20

	# Buildings
	[[maps.layers]]
	name = "buildings"
	provider_layer = "osm.buildings"
	min_zoom = 14
	max_zoom = 20
